matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - nschloe-cmake-nightly
          packages:
            - g++-7
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
language: c
before_install:
  - eval "${MATRIX_EVAL}"
  - mkdir build
  - cd build
  - cmake ..
install:
  - cd build
  - make
script:
  - cd build
  - ctest -V
