language: generic
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:nschloe/cmake-nightly'
          packages:
            - g++-7
            - cmake
      env:
        - CC=gcc-7 CXX=g++-7
before_install:
  - pip install --user pytest
  - mkdir build
  - cd build
install:
  - cmake ..
  - make
script:
  - ctest -V
