language: generic
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:nschloe/cmake-nightly'
          packages:
            - g++-7
            - valgrind
            - cmake
      env:
        - CC=gcc-7 CXX=g++-7
install:
  - cmake .
  - make
script:
  - ctest -V
